### ISSUE TITLE
Question marks on map

### ISSUE THREAD

**Issue by MD5-Hashm** [nogizhopaboroda/iponmap#6] opened 2020-10-07 15:21 UTC
I know its been awhile since this came out but i think its really cool. I have one issue, Where the dots are supposed to be there are question marks. View attached screenshot

[](url)
![Capture](https://user-images.githubusercontent.com/47696465/95351437-38ba2180-088f-11eb-99bd-47cf87cc3531.PNG)

**Comment by MD5-Hashm** [comment] 2020-10-08 13:30
@nogizhopaboroda

**Comment by nogizhopaboroda** [comment] 2020-10-08 19:01
duplicate of https://github.com/nogizhopaboroda/iponmap/issues/3

**Comment by nogizhopaboroda** [comment] 2020-10-08 19:03
hi @MD5-Hashm 
thanks for the report
i think the issue here is caused by your terminal. some encoding missing or so. 
is it windows?
could you please try this solution https://github.com/yaronn/blessed-contrib#troubleshooting and tell if it helps?
in your case:
```sh
LANG=en_US.utf8 TERM=xterm-256color iponmap
```

**Comment by MD5-Hashm** [comment] 2020-10-09 12:35
'LANG' is not recognized as an internal or external command,
operable program or batch file.

Thats the error after I put that into my cmd

(Sorry i'm the greatest at this)

**Comment by MD5-Hashm** [comment] 2020-10-09 12:39
And its windows

**Comment by MD5-Hashm** [comment] 2020-10-09 12:46
Also if I'm right I'm pretty sure Lang is only for bash

**Comment by MD5-Hashm** [comment] 2020-10-10 01:01
I have found a way to change the encoding to utf 8 within windows but the question marks still show up

**Comment by MD5-Hashm** [comment] 2020-10-10 01:12
I also tried installing a braille font but to no avail

**Closed as not planned** 2022-06-14 11:20 UTC
Labels: duplicate
